[package]
name = "cargo-binutils"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]

[dependencies]
failure = "0.1.1"
regex = "0.2.10"
rustc-demangle = "0.1.7"
rustc_version = "0.2.2"
serde = "1.0.37"
serde_derive = "1.0.37"
toml = "0.4.6"
