[package]
edition = "2018"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["command-line-utilities", "development-tools"]
description = "Proxy for LLVM tools like llvm-nm, llvm-objdump and llvm-size"
documentation = "https://github.com/rust-embedded/cargo-binutils#cargo-binutils"
keywords = ["llvm", "size", "objdump", "nm"]
license = "MIT OR Apache-2.0"
name = "cargo-binutils"
readme = "README.md"
repository = "https://github.com/rust-embedded/cargo-binutils/"
version = "0.2.0"

[dependencies]
cargo_metadata = "0.10.0"
clap = "2.33.0"
failure = "0.1.7"
regex = "1.3.6"
rustc-cfg = "0.4.0"
rustc-demangle = "0.1.16"
rustc_version = "0.2.3"
serde = "1.0"
toml = "0.5.6"
